// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBow5MgafFvhJkp3EcnXmj0OJKVM1Q0hBs',
    appId: '1:1069713958251:web:ac6df97947693e355a982e',
    messagingSenderId: '1069713958251',
    projectId: 'eclipse-ice',
    authDomain: 'eclipse-ice.firebaseapp.com',
    storageBucket: 'eclipse-ice.appspot.com',
    measurementId: 'G-3CGX4C27LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVD4SeuH3IEYlNToy2jLeq8wCQtW-6ZIY',
    appId: '1:1069713958251:android:d7519d43f48340765a982e',
    messagingSenderId: '1069713958251',
    projectId: 'eclipse-ice',
    storageBucket: 'eclipse-ice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRygF33ftAJscoQGWjeuA5iAkjwXaSAXw',
    appId: '1:1069713958251:ios:44ef1fd5b8e3a19c5a982e',
    messagingSenderId: '1069713958251',
    projectId: 'eclipse-ice',
    storageBucket: 'eclipse-ice.appspot.com',
    iosBundleId: 'com.eclipse.ice.ice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBow5MgafFvhJkp3EcnXmj0OJKVM1Q0hBs',
    appId: '1:1069713958251:web:a614504a3cbebc385a982e',
    messagingSenderId: '1069713958251',
    projectId: 'eclipse-ice',
    authDomain: 'eclipse-ice.firebaseapp.com',
    storageBucket: 'eclipse-ice.appspot.com',
    measurementId: 'G-EP0PJ4TT28',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRygF33ftAJscoQGWjeuA5iAkjwXaSAXw',
    appId: '1:1069713958251:ios:44ef1fd5b8e3a19c5a982e',
    messagingSenderId: '1069713958251',
    projectId: 'eclipse-ice',
    storageBucket: 'eclipse-ice.appspot.com',
    iosBundleId: 'com.eclipse.ice.ice',
  );

}